compile:
	gcc -o prog prog.c $(CFLAGS) -DTERAPIE_VARIABILI -DFLUSSO_COVID_VARIABILE -DCOOPERAZIONE_OSPEDALI -DABILITA_AGGRAVAMENTO -DABILITA_TIMEOUT -DGEN_RT -lpthread -lm
stat:
	gcc -o teststat stat.c -DTESTSTAT